kind: Route
apiVersion: v1
metadata: 
  name: python
spec:
  port:
    targetPort: pythonport
  to:
    kind: Service
    name: python
#oc login
#oc annotate route python haproxy.router.openshift.io/balance='roundrobin'