kind: BuildConfig
apiVersion: v1
metadata:
  name: python
spec:
  runPolicy:  Serial
  source:
    git:
      uri:  https://github.com/sjeeva/flaskapp.git
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStream
      name: python